site_name: precision-medicine-toolbox
nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - API:
    - Imaging class: DataSet.md
    - Imaging module: ToolBox.md
    - Features class: FeaturesSet.md
    - Features module: AnalysisBox.md
    - Classification result class: ResultSet.md
    - Classification result module: GenerateResultBox.md
theme: readthedocs
docs_dir: 'docs'
site_dir: 'site'
plugins:
  - search
  - mkdocstrings:
      handlers:
        python
copyright: Copyright &copy; 2019 - 2022, Sergey Primakov & Lisa Lavrova.